insert into public.cursos_aula (codigo, titulo, nivel)
values
  ('MATA-01', 'Razonamiento Matemático', 'preuniversitaria'),
  ('MATA-02', 'Aritmética', 'preuniversitaria'),
  ('MATA-03', 'Álgebra', 'preuniversitaria'),
  ('MATA-04', 'Trigonometría', 'preuniversitaria'),
  ('MATA-05', 'Geometría', 'preuniversitaria'),
  ('LENA-01', 'Lenguaje', 'preuniversitaria'),
  ('LENA-02', 'Literatura', 'preuniversitaria'),
  ('LENA-03', 'Razonamiento Verbal', 'preuniversitaria'),
  ('SOCA-01', 'Psicología', 'preuniversitaria'),
  ('SOCA-02', 'Educación Cívica', 'preuniversitaria'),
  ('SOCA-03', 'Historia del Perú', 'preuniversitaria'),
  ('SOCA-04', 'Historia Universal', 'preuniversitaria'),
  ('SOCA-05', 'Geografía', 'preuniversitaria'),
  ('SOCA-06', 'Economía', 'preuniversitaria'),
  ('SOCA-07', 'Filosofía', 'preuniversitaria'),
  ('NATA-01', 'Física', 'preuniversitaria'),
  ('NATA-02', 'Química', 'preuniversitaria'),
  ('NATA-03', 'Biología', 'preuniversitaria'),
  ('INGA-01', 'Inglés', 'preuniversitaria'),
  ('MATS-01', 'Razonamiento Matemático', 'secundaria'),
  ('MATS-02', 'Aritmética', 'secundaria'),
  ('MATS-03', 'Álgebra', 'secundaria'),
  ('MATS-04', 'Trigonometría', 'secundaria'),
  ('MATS-05', 'Geometría', 'secundaria'),
  ('LENS-01', 'Lenguaje', 'secundaria'),
  ('LENS-02', 'Literatura', 'secundaria'),
  ('LENS-03', 'Razonamiento Verbal', 'secundaria'),
  ('NATS-01', 'Física', 'secundaria'),
  ('NATS-02', 'Química', 'secundaria'),
  ('NATS-03', 'Biología', 'secundaria'),
  ('INGS-01', 'Inglés', 'secundaria'),
  ('MATP-01', 'Razonamiento Matemático', 'primaria'),
  ('MATP-02', 'Aritmética', 'primaria'),
  ('MATP-03', 'Álgebra', 'primaria'),
  ('MATP-04', 'Geometría', 'primaria'),
  ('LENP-01', 'Lenguaje', 'primaria'),
  ('LENP-02', 'Comprensión Lectora', 'primaria'),
  ('LENP-03', 'Razonamiento Verbal', 'primaria'),
  ('SOCP-01', 'Personal Social', 'primaria'),
  ('NATP-01', 'Ciencia y tecnología', 'primaria'),
  ('INGP-01', 'Inglés', 'primaria')
on conflict (codigo) do update
set
  titulo = excluded.titulo,
  nivel = excluded.nivel;
